# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_pass', models.CharField(max_length=8)),
                ('user_fname', models.CharField(max_length=240)),
                ('user_lname', models.CharField(max_length=240)),
                ('user_address', models.CharField(max_length=240)),
                ('user_city', models.CharField(max_length=240)),
                ('user_prov', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MN', 'Manitoba'), ('NB', 'New Brunswick'), ('NS', 'Nova Scotia'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YK', 'Yukon'), ('NU', 'Nunavut'), ('NT', 'Northwest Territories')], max_length=240)),
                ('user_country', models.CharField(max_length=240)),
                ('user_phone_mobile', models.CharField(blank=True, default='', max_length=240)),
                ('user_phone_home', models.CharField(blank=True, default='', max_length=240)),
                ('user_payment_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_default_pay', models.BooleanField(default=False)),
                ('payment_default_receive', models.BooleanField(default=False)),
                ('payment_account_type', models.CharField(choices=[('Visa', 'Visa'), ('Master', 'Mastercard'), ('Amex', 'AMEX'), ('Bank', 'Bank Account')], max_length=240)),
                ('payment_account_info', models.CommaSeparatedIntegerField(max_length=240)),
                ('payment_account_expiry', models.CommaSeparatedIntegerField(max_length=7)),
                ('payment_account_verified', models.BooleanField(default=False)),
                ('payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
