# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20160312_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal_gluent_free',
            new_name='meal_gluten_free',
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_spice_level',
            field=models.CharField(choices=[('L', 'Mild'), ('M', 'Medium'), ('H', 'Hot'), ('O', 'Other')], default='Other', max_length=240),
        ),
    ]
